apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bot.name }}-secret
type: Opaque
data:
  TG_BOT_TOKEN: {{ .Values.bot.tgToken | b64enc }}
  DATABASE_URI: {{ printf "%s+%s://%s:%s@%s-service:%d/%s" 
  .Values.bot.db.type
  .Values.bot.db.driver
  .Values.database.user
  .Values.database.password
  .Values.database.name
  (.Values.database.port | int64 )
  .Values.database.dbname | b64enc | quote }}
  {{- with .Values.kv_database }}
  KV_DATABASE_URI: {{ printf "%s://@%s-service:%d/%d" 
  .name
  .name
  (.port | int64 ) 
  (.db | int64 ) | b64enc | quote}}
  {{- end }}