apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.kv_database.name }}-service"
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.kv_database.components }}
  ports:
  - port: {{ .Values.kv_database.port }}