[tool.poetry]
name = "bot-anketa"
version = "0.1.0"
description = ""
authors = ["nezbut_ubuntu <dsfsdfsdf.sdfsdfsfdf.98@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
